package com.google.android.gms.p031b;

import com.google.android.gms.common.api.C1713d;
import com.google.android.gms.common.api.C1713d.C1709a;
import com.google.android.gms.common.api.C1780h;
import com.google.android.gms.common.api.C1857g;
import com.google.android.gms.common.api.Status;

public class nc<R extends C1857g> extends C1713d<R> {
    private final Status f6023a;

    public Integer mo1546a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void mo1547a(C1709a c1709a) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public void mo1548a(C1780h<? super R> c1780h) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    Status m10093b() {
        return this.f6023a;
    }
}
